# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
#logo: /AnswersFromGod/images/Answers_From_God_500x379_gold_top.jpg
logo: /images/Answers_From_God_500x379_gold_top.jpg

# Header
menu:
  #Home: /AnswersFromGod/
  Home: /
  Categories:
  Questions Answered: /FAQ/index.html
  Links: /links/index.html
  About: /about/index.html

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
social_links:
  #email: mailto:Christian@AnswersFromGod.com?Subject=Blog%20Contact
  email: /EmailSubscribe/index.html
  #twitter:
  #facebook:
  #google_plus:
  #github: http://servantofyehovah.github.io/AnswersFromGod
  #weibo:
  #rss:
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Answers From God: http://amzn.to/1KiS8lM

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics: UA-63184318-1
#favicon: /favicon.png
#fb_admins:
#fb_app_id:

# Language
#language: en-US

# Comments
comment_provider: disqus
